<?php
/**
 * Copyright (C) EC Brands Corporation - All Rights Reserved
 * Contact Licensing@ECInternet.com for use guidelines
 */
declare(strict_types=1);
?>

<?php /** @var \ECInternet\Sage300Account\Block\Catalog\Product\View $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<?php if ($block->showBlock()) { ?>
<div class="product-info-uom">
    <div class="product attribute uom">
        <strong>UOM</strong>
        <span class="value" itemprop="uom">
            <?= $escaper->escapeHtml($block->getUomDisplayValue()) ?>
        </span>
    </div>
</div>
<?php } ?>
